name: drift_testcases
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.0.0-0
  json_annotation: ^4.5.0
  test: ^1.22.0

dev_dependencies:
  build_runner: ^2.1.11
  drift_dev: ^2.0.0
  json_serializable: ^6.2.0
  lints: ^2.0.0
