# We use netlify to deploy the documentation.

[build]
  publish = "docs/deploy"

[[redirects]]
  from = "https://moor.netlify.app/*"
  to = "https://drift.simonbinder.eu/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://moor.simonbinder.eu/*"
  to = "https://drift.simonbinder.eu/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/name"
  to = "/docs/upgrading/#name"
  status = 301
  force = true

[[redirects]]
  from = "/docs/getting-started/starting_with_sql/"
  to = "/docs/sql-api/#setup"
  status = 301
  force = true

[[redirects]]
  from = "/docs/advanced-features/joins/"
  to = "/docs/dart-api/select/#joins"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[context.production]
  environment = { BUILD_RELEASE="release" }

[context.deploy-preview]
  environment = {  }
