name: web_worker_example
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  js: ^0.6.4
  stream_channel: ^2.1.0
  drift:

dev_dependencies:
  build_runner: ^2.1.11
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
  drift_dev:
