name: drift_postgres
description: Postgres support for drift
version: 1.0.0

environment:
  sdk: '>=2.12.0-0 <4.0.0'

dependencies:
  collection: ^1.16.0
  drift: ^2.0.0
  postgres:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.18.0
  drift_testcases:
    path: ../integration_tests/drift_testcases

dependency_overrides:
  drift:
    path: ../../drift
  postgres:
    git:
      url: https://github.com/isoos/postgresql-dart.git
